apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends-app
  name: techtrends-app
  namespace: project-test 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends-app-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends-app-pod
    spec:
      containers:
      - image: ehabhamdy/techtrends:latest 
        imagePullPolicy: IfNotPresent
        name: techtrends-app
        # resources:
        #   requests:
        #     cpu: 250m
        #     memory: 64Mi

      - containerPort: 3111
          protocol: TCP

      livenessProbe:
           httpGet:
             path: /healthz
             port: TCP

      readinessProbe:
           httpGet:
             path: /health
             port: TCP

      requests:
            memory: "64Mi"
            cpu: "250m"

      limits:
            memory: "128Mi"
            cpu: "500m"
