apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends-app
  name: techtrends-app
  namespace: project-test 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends-app
    spec:
      containers:
      - image: ehabhamdy/techtrends:latest 
        imagePullPolicy: IfNotPresent
        name: techtrends-app
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          
          limits:
            cpu: "500m"
            memory: "128Mi"

        ports:
        - containerPort: 3111
          protocol: TCP

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111

   
