apiVersion: v1

kind: Service

metadata:
  labels:
    app: techtrends-app
  name: techtrends-app
  namespace: project-test

spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends-app-pod
  type: ClusterIP