apiVersion: v1

kind: Service

metadata:
  labels:
    app: techtrends-app
  name: techtrends-app
  namespace: default

spec:
  ## Define the ports that the service should serve on. 
  ## For example, the service is exposed on port 8111, and
  ## directs the traffic to the pods on port 6112, using TCP.
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  ## Identify the pods managed by this Service using the following selectors.
  ## In this case, all pods with the label `go-helloworld`.
  selector:
    app: techtrends-app-pod
  ## Define the Service type, here set to ClusterIP.
  type: ClusterIP